### ISSUE TITLE
SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by Abc11c** [yongchao98/AutoTAMP#1]
Hi @yongchao98,

Thanks for releasing the code!
I quickly tested this using the command  `python autotamp_single_agent.py`

I keep running into errors [here](https://github.com/yongchao98/AutoTAMP/blob/cbe6d7dc00748d9fbc091f9c95f1fee9cbb07278/env_and_optimize_single_agent.py#L372)

```
SyntaxError: EOL while scanning string literal

Output from GPT looks like

"['and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and', 'and"
```
The issue is with `ast.literal_eval` ? 

Have you come across such a issue? 

Thanks!

**Comment by yongchao98** [comment]
Hello thanks for your comments. The issue sometimes happens when using GPT-3 not GPT-4 or the task situation is quite different from the few-show examples. One solution is adding more few-show examples.

We have updated the code and also the testing examples in the experiment_result dir. Please try the code again. We believe right now it is fine.

**Comment by Abc11c** [comment]
Yes!, few-shot translation examples with gpt4 seem to fix it. 

Also how to generate images as seen in the paper I see a `vis.py` but I don't see it being called anywhere.

Thanks, @yongchao98

**Comment by yongchao98** [comment]
Hello,

Thanks for your question and sorry for the late reply. We have uploaded the AutoTAMP_plotting.ipynb and Example_results directory to give the visualization examples. During the experiments, myfile0.txt will be created to record the position/time waypoints, which are used for visualization when giving the environmental plots.

Best,
Yongchao
